# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: |
    sudo apt-add-repository --yes ppa:dartsim/ppa
    sudo apt-get -qq update
    sudo apt-get -qq --yes install build-essential cmake pkg-config git
    sudo apt-get -qq --yes install libeigen3-dev libassimp-dev libccd-dev libfcl-dev libboost-filesystem-dev libboost-regex-dev libboost-system-dev
    sudo apt-get -qq --yes install libopenscenegraph-dev
    mkdir build
    cd build
    cmake ..
    make
  displayName: 'make'
